/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ClaimstonePortalAPIV1 {
  "/admin": Admin;
  "/error": Error;
  "/meta": Meta;
  "/projects": Projects;
  "/projects/{p}/activity": Activity;
  "/projects/{p}/integrity": Integrity;
  "/projects/{p}/poll": Poll;
  "/projects/{p}/{sel}/claims/{claim_id}": Lineage;
  "/projects/{p}/{sel}/inbox": Inbox;
  "/projects/{p}/{sel}/overview": Overview;
  "/projects/{p}/{sel}/questions/{qid}": QuestionDetail;
  "/projects/{p}/{sel}/questions/{qid}/profile-diff": ProfileDiff;
  "/projects/{p}/{sel}/sources/{candidate_key}": SourceDossier;
  "/projects/{p}/{sel}/summary": Summary;
}
export interface Admin {
  api_version: 1;
  backends: {
    available: string[];
    configured: string[];
  };
  backends_note: string;
  credentials: {
    [k: string]: boolean;
  };
  instruments: {
    [k: string]: number | string;
  };
  key_rotation_note: string;
}
export interface Error {
  api_version: 1;
  error: {
    code:
      | "BAD_REQUEST"
      | "NOT_FOUND"
      | "CONFIG_ERROR"
      | "REGISTRY_DRIFT"
      | "LEDGER_CORRUPT"
      | "MISDIRECTED"
      | "CROSS_ORIGIN"
      | "INTERNAL";
    message: string;
  };
}
export interface Meta {
  api_version: 1;
  code: {
    dirty: boolean | null;
    revision: string | null;
  };
  instruments: {
    [k: string]: number | string;
  };
  started_at: string;
}
export interface Projects {
  api_version: 1;
  projects: {
    config: "OK" | "ConfigError";
    config_error: string | null;
    flows?: {
      binding_state: "CURRENT" | "REGISTRY_DRIFTED" | "PROTOCOL_DRIFTED" | "POPULATION_DRIFTED";
      bound_after_data: boolean;
      flow_id: string;
      selector: {
        manifest_only: boolean;
        round: string | null;
      };
      selector_label: string;
      title: string | null;
    }[];
    integrity_error?: string | null;
    name: string;
    registry_drift?: string | null;
    registry_sha256?: string;
    registry_version?: number;
    unbound_selectors?: {
      label: string;
      selector: {
        manifest_only: boolean;
        round: string | null;
      };
      slug: string;
    }[];
    [k: string]: unknown;
  }[];
}
export interface Activity {
  activity: {
    ledger: string;
    row: {
      [k: string]: unknown;
    };
    stage: string;
    when: string;
  }[];
  api_version: 1;
  project: string;
}
export interface Integrity {
  api_version: 1;
  code: {
    dirty: boolean | null;
    grobid_image: string;
    revision: string | null;
  };
  config: {
    error: string | null;
    state: "OK" | "ConfigError";
  };
  instruments: string[];
  invalid_flows: string[];
  ledger_repairs: number;
  ledgers: {
    [k: string]: {
      error: string | null;
      rows: number;
      torn_tail: boolean;
    };
  };
  orphans: number | null;
  project: string;
  registry: {
    error: string | null;
    state: "OK" | "RegistryDrift";
  };
}
export interface Poll {
  api_version: 1;
  ledgers: {
    [k: string]: {
      mtime: string | null;
      rows: number | null;
    };
  };
  pid_note: string;
  project: string;
  running: string[];
}
export interface Lineage {
  api_version: 1;
  claim_id: string;
  project: string;
  selector: {
    manifest_only: boolean;
    round: string | null;
  };
  source_id: string;
  steps: {
    acquisition: {
      attempts: {
        failure_display: string;
        fetch_version: number;
        http_status: number | null;
        url: string | null;
        [k: string]: unknown;
      }[];
      [k: string]: unknown;
    } | null;
    acquisition_candidate_key: string | null;
    candidate: {
      [k: string]: unknown;
    } | null;
    chunk: {
      chunk_id: string;
      evidence_quote: string;
      generation_sha256: string | null;
      quote_found: boolean;
      text: string | null;
      text_sha256: string | null;
    } | null;
    claim: {
      [k: string]: unknown;
    };
    document: {
      [k: string]: unknown;
    } | null;
    document_pdf_instrument: string | null;
    review: {
      [k: string]: unknown;
    } | null;
  };
}
export interface Inbox {
  api_version: 1;
  cards: {
    category:
      | "INTEGRITY"
      | "PROTOCOL"
      | "ACQUISITION"
      | "CLASSIFICATION"
      | "NORMALIZE"
      | "EXTRACT"
      | "REVIEW"
      | "ADJUDICATION"
      | "ADVISORY";
    cause: string;
    command: string | null;
    note: string;
    scope: string;
    subject: string;
  }[];
}
export interface Overview {
  activity: {
    ledger: string;
    row: {
      [k: string]: unknown;
    };
    stage: string;
    when: string;
  }[];
  api_version: 1;
  binding_state: {
    bound_after_data: boolean;
    differences: string[];
    state: "CURRENT" | "REGISTRY_DRIFTED" | "PROTOCOL_DRIFTED" | "POPULATION_DRIFTED";
  } | null;
  errors: string[];
  floor_panel: {
    by_class: {
      [k: string]: unknown;
    };
    disclosure: string;
    overall: {
      [k: string]: unknown;
    };
    sentences: string[];
  } | null;
  flow: {
    [k: string]: unknown;
  } | null;
  inbox: {
    category:
      | "INTEGRITY"
      | "PROTOCOL"
      | "ACQUISITION"
      | "CLASSIFICATION"
      | "NORMALIZE"
      | "EXTRACT"
      | "REVIEW"
      | "ADJUDICATION"
      | "ADVISORY";
    cause: string;
    command: string | null;
    note: string;
    scope: string;
    subject: string;
  }[];
  legacy: boolean;
  project: string;
  question_state_counts: {
    awaiting_a_person: number;
    historical: number;
    no_profile: number;
    no_verified_claim: number;
    not_applicable: number;
    provisional: number;
    signed: number;
    stale: number;
  };
  questions: {
    project: string;
    round: string | null;
    rows: {
      awaiting_review: number;
      blocking: string[];
      claims: number | null;
      claims_by_class: {
        [k: string]: number;
      };
      coverage: {
        examined: number | null;
        sources: number | null;
      };
      direction_count: {
        [k: string]: unknown;
      };
      direction_count_note: string;
      display_state:
        | "signed"
        | "stale"
        | "awaiting_a_person"
        | "provisional"
        | "no_verified_claim"
        | "not_applicable"
        | "historical"
        | "no_profile";
      extraction: {
        [k: string]: unknown;
      } | null;
      gate_rejected: {
        [k: string]: unknown;
      };
      gate_rejected_total: number;
      id: string;
      kind: string;
      note: string | null;
      operational_not_applicable: boolean;
      profile_sha256: string | null;
      provisional: boolean;
      state: string | null;
      stored_profile_stale: boolean;
      text: string;
      unavailable: string;
      verdict:
        null | "SUPPORTED" | "CONTRADICTED" | "CONTESTED_IN_LITERATURE" | "UNANSWERED_IN_LITERATURE" | "NEVER_ASKED";
      verdict_stale: boolean;
    }[];
  };
  selector: {
    manifest_only: boolean;
    round: string | null;
  };
  selector_label: string;
  source_tracker: {
    candidate_key: string;
    source_class: string;
    source_id: string | null;
    state: "confirmed" | "awaiting_normalize" | "not_a_document" | "not_obtained" | "not_attempted" | "unclassified";
    tooltip: string;
  }[];
  state: {
    errors: string[];
    floor: {
      [k: string]: unknown;
    } | null;
    project: string;
    questions: {
      [k: string]: unknown;
    }[];
    rejections_by_reason: {
      [k: string]: unknown;
    };
    round: string | null;
    stages: {
      [k: string]: unknown;
    }[];
    unavailable: string;
    verdicts_recorded: number;
    verdicts_stale: number;
  };
  unavailable: string;
}
export interface QuestionDetail {
  adjudication_card: {
    category:
      | "INTEGRITY"
      | "PROTOCOL"
      | "ACQUISITION"
      | "CLASSIFICATION"
      | "NORMALIZE"
      | "EXTRACT"
      | "REVIEW"
      | "ADJUDICATION"
      | "ADVISORY";
    cause: string;
    command: string | null;
    note: string;
    scope: string;
    subject: string;
  } | null;
  api_version: 1;
  id: string;
  kind: string;
  not_applicable_state: string | null;
  operational_not_applicable: boolean;
  profile: {
    [k: string]: unknown;
  };
  profile_fields: {
    awaiting_review: number;
    blocking: string[];
    coverage: {
      [k: string]: unknown;
    };
    direction_count: {
      [k: string]: unknown;
    };
    direction_count_note: string;
    extraction: {
      [k: string]: unknown;
    } | null;
    gate_rejected: {
      [k: string]: unknown;
    };
    linkage: unknown;
    profile_sha256: string | null;
    provisional: boolean | null;
    reviewed_not_usable: {
      [k: string]: unknown;
    };
    state: string | null;
    stored_profile_stale: boolean;
    unavailable: string;
  };
  project: string;
  results: {
    [k: string]: unknown;
  }[];
  selector: {
    manifest_only: boolean;
    round: string | null;
  };
  text: string;
  verdict: {
    adjudicated_at: string;
    adjudicated_by: string;
    decision_contract_version: number | null;
    manifest_only: boolean;
    profile_sha256: string;
    question_id: string;
    rationale: string;
    registry_sha256: string | null;
    registry_version: number | null;
    round: string | null;
    verdict: "SUPPORTED" | "CONTRADICTED" | "CONTESTED_IN_LITERATURE" | "UNANSWERED_IN_LITERATURE" | "NEVER_ASKED";
  } | null;
  verdict_stale: boolean;
}
export interface ProfileDiff {
  added: {
    [k: string]: unknown;
  }[];
  api_version: 1;
  changed: {
    [k: string]: unknown;
  }[];
  counts: {
    from: {
      by_class: {
        [k: string]: unknown;
      };
      direction_count: {
        [k: string]: number;
      };
    };
    to: {
      by_class: {
        [k: string]: unknown;
      };
      direction_count: {
        [k: string]: number;
      };
    };
  };
  from: {
    built_at: string;
    claim_gate_version: number;
    decision_contract_version: number;
    profile_sha256: string;
    registry_version: number;
  };
  id: string;
  project: string;
  reason: string | null;
  removed: {
    [k: string]: unknown;
  }[];
  selector: {
    manifest_only: boolean;
    round: string | null;
  };
  summary: {
    added: number;
    changed: number;
    removed: number;
  };
  to: {
    built_at: string;
    claim_gate_version: number;
    decision_contract_version: number;
    profile_sha256: string;
    registry_version: number;
  };
}
export interface SourceDossier {
  acquisitions: {
    attempts: {
      failure_display: string;
      fetch_version: number;
      http_status: number | null;
      url: string | null;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  }[];
  active_chunks: number | null;
  advisory: {
    [k: string]: {
      [k: string]: unknown;
    }[];
  };
  advisory_note: string;
  api_version: 1;
  candidate: {
    [k: string]: unknown;
  } | null;
  candidate_key: string;
  claims_by_question: {
    [k: string]: number;
  };
  counted_acquisition: {
    [k: string]: unknown;
  } | null;
  document: {
    [k: string]: unknown;
  } | null;
  project: string;
  selector: {
    manifest_only: boolean;
    round: string | null;
  };
  source_id: string;
}
export interface Summary {
  api_version: 1;
  floor_status: string | null;
  flow_id: string | null;
  inbox_counts: {
    [k: string]: number;
  };
  project: string;
  selector: {
    manifest_only: boolean;
    round: string | null;
  };
  selector_label: string;
  verdicts: {
    adjudicated: number;
    awaiting_adjudication: number;
    stale: number;
  } | null;
}
